### ISSUE TITLE
Whitelist --no-update option for require and remove commands

### ISSUE THREAD

**Issue by Toflar** [tenside/core-bundle#11]

**Comment by discordier** [comment]
Should be fixed with tenside/core@1b0410dbf111fda36e225b7fadafd4911559c0f2

**Comment by Toflar** [comment]
Yeah, somewhat it does not work though, see https://github.com/tenside/core/issues/16 :)

**Comment by discordier** [comment]
That's why I closed this one, you created a new issue.
Will get to it ASAP
