### ISSUE TITLE
The API endpoints are not consistent yet

### ISSUE THREAD

**Issue by Toflar** [tenside/core-bundle#13]
Some of the API endpoints return an object in the manner of

```json
{
   "status": "OK"
   "whatever-content" {
   }
}
```

But some do not:

* Search endpoint just returns the packages without a status
* Task endpoint returns the status of the task (RUNNING, FINISHED etc.) but no status for the request itself

Can we unify this? And that being said, get trid of this `response.status` completely? That's the task of the HTTP status code there.

**Comment by Toflar** [comment]
One problem is this: https://github.com/contao/package-manager/commit/3e45ec9ead444c5e92ef90e02c42405cf328f4cb

I cannot unify the way a request is considered to be OK or not. And to me, anything between 200 and 300 actually is OK but right now, I also get 200 OK at some points if "response.status" is "ERROR"...

**Comment by aschempp** [comment]
>  I also get 200 OK at some points if "response.status" is "ERROR"...

That's just horribly wrong, be **must** use HTTP status codes!

**Comment by discordier** [comment]
>> I also get 200 OK at some points if "response.status" is "ERROR"...

> That's just horribly wrong, be must use HTTP status codes!

I assume you are talking about the `/v1/constraint` endpoint and the other validating endpoints here.
Can you shed some light how the endpoint shall behave here?
I mean, you post an invalid constraint and want it to be validated.
The request against the API was in this case successful, however, the information you expect to get will be "error, your constraint was invalid". Putting an result code of `400 Bad request` here is against RFC which states:
> The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications.

You see, the request is perfectly valid, however, the resulting document MUST indicate if the operation RESULT is valid or not.

The introduction of putting a status field on every response payload resulted from the fact that the API SHOULD become consistent and return the same document structure on every call (apparantly search was forgotten).

I am all open to scrape the status from the responses, however the validating endpoints will still need them, I am afraid

**Comment by discordier** [comment]
@Toflar Can we close this? you altered the endpoints some time ago.

**Comment by Toflar** [comment]
👍
