### ISSUE TITLE
Autoconfig takes forever

### ISSUE THREAD

**Issue by aschempp** [tenside/core-bundle#15]
The `autoconfig` route takes more than 10 seconds to complete. Any idea why this takes so long?

**Comment by discordier** [comment]
Nope, but you can trace through the various self-tests.

I suspect the scan for the PHP binary to scan your whole filesystem or something like that.

**Comment by discordier** [comment]
As it turned out, it is the `SelfTestCliRuntime` which runs crucially slow on MAMP.

Nothing we can fix I assume.

Further reading on stackoverflow suggests to disable the `zend_opcache` and `imap` extensions in `php.ini`.
