### ISSUE TITLE
Configure should optionally take a secret

### ISSUE THREAD

**Issue by Toflar** [tenside/core-bundle#2]
I think it's wrong to force passing a secret. Tenside itself should take care of generating a secure one if not passed by the API. Otherwise I have to embed some JS library to generate a truly random secret because we are certainly not going to ask the end user for a secret but generate one.

**Comment by discordier** [comment]
We should provide the end user with a way to pass one. It feels wrong hiding it from them completely.
However, we can generate it when none has passed though.

**Comment by Toflar** [comment]
Yes, please :)
