### ISSUE TITLE
Implement sorting by name or last updated

### ISSUE THREAD

**Issue by Toflar** [tenside/core-bundle#5]
Our packages overview allows ordering search results (no matter whether installed or not) by either name alphabetically or the date it was last updated.
This has to be implemented (or added to the api doc if already there).
![bildschirmfoto 2016-04-05 um 19 00 13](https://cloud.githubusercontent.com/assets/481937/14290787/d0b4cbac-fb60-11e5-9b8b-399a30288e13.png)

/cc @aschempp

**Comment by aschempp** [comment]
Imho that should be a GUI problem, not for the API

**Comment by Toflar** [comment]
If I can get them pre-sorted, why not? :)

**Comment by aschempp** [comment]
Just because the tenside API is supposed to be universal, and we dont want to implement any sorting option every UI can think of…

It depends on the pagination though...

**Comment by Toflar** [comment]
Composer search already supports sorting so I don't understand why we would not want to use it.

**Comment by discordier** [comment]
@toflar the search is not sorted. The `RepositoryInterface` does not support it. Where do you get the information from that it supports sorting? Do you know more than me?

**Comment by Toflar** [comment]
Well, on packagist you can order by downloads and stars, I thought it is built in then. But if you tell me that it's better to sort in JS, I can do that, no prob :)

**Comment by Toflar** [comment]
I think this has to be implemented at least for the /packages endpoint because it's kind of strange not to see your installed packages alphabetically sorted.
