### ISSUE TITLE
Tenside spams folder with tasks

### ISSUE THREAD

**Issue by Toflar** [tenside/core-bundle#8]
We need a routine that cleans up old tasks. What do you think about a config value like `tasks.limit` which is then considered when creating a new task? (Delete all but the `task.limit` number of latest tasks) Otherwise Tenside bloats up my tenside folder.

/cc @aschempp

**Comment by discordier** [comment]
You are responsible for deleting runned tasks when you retrieved all the output from the ui.
We have no way to know if you have obtained all of the log and therefore do not delete tasks on our own.

**Comment by Toflar** [comment]
What if things go wrong?

**Comment by discordier** [comment]
You can see it in the info of the task if it failed.
If so, you have to delete it.

**Comment by Toflar** [comment]
If it's pending forever? I think we should add at least a date when it was startet so we can e.g. clean up all tasks that are running for over a week or so :D

**Comment by Toflar** [comment]
*bump* I think I'd like to be able to fire a request to cleanup for tasks older than a week every once in a while.

**Comment by aschempp** [comment]
Is that really something the UI should do? Sounds like an internal maintenance task similar to aelf update.

**Comment by Toflar** [comment]
Yeah, that's what I think too. Tenside should make sure it's in clean state, not the UI. But @discordier said I need to execute delete requests. My opinion is the same, it should take care of this on its own. It's like Contao's reviseTable stuff. Cleaning up orphans.

**Comment by aschempp** [comment]
Certainly not a UI task

**Comment by discordier** [comment]
As discussed with @Toflar, we will add the `created-at` information to the task data and the UI will delete everything it does not want anymore.
